version: "2"

linters:
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "SA1019:"
      - linters:
          - errcheck
        text: "Error return value of `.*\\.Close` is not checked"